ASP-651
airly-eu/api-docs pull request #11
Opened 2022-10-12 13:34 UTC by MaciejGrochowski

2022-10-12 15:47 UTC, maraswrona requested changes

2022-10-12 15:47 UTC, maraswrona commented on en/endpoints.measurements.md
> +- **indexPollutant** - selects the set of pollutant types considered which calculating value of the index; currently supported values are PM (default = {PM10, PM25), PM10, PM25, O3, NO2, SO2, CO, ALL
... considered **when** calculating ... ?
also wrong bracket around PM values

2022-10-12 21:02 UTC, DCzajkowski commented on en/endpoints.measurements.md
> +- **indexPollutant** - selects the set of pollutant types considered which calculating value of the index; currently supported values are PM (default = {PM10, PM25), PM10, PM25, O3, NO2, SO2, CO, ALL
Missing closing curly brace

2022-10-13 10:59 UTC, maraswrona approved these changes

2022-10-13 11:08 UTC, merged